# Generated by Django 5.1.4 on 2025-01-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='file_path',
            field=models.CharField(default=1, help_text='Path to the stored file on disk or cloud storage', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.TextField(blank=True, help_text='Base64 encoded file content', null=True),
        ),
    ]
