# Generated by Django 5.1.4 on 2025-01-08 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bookmarked_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('authors', models.JSONField()),
                ('source', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('pdf_url', models.URLField(blank=True, null=True)),
                ('categories', models.JSONField(default=list)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bookmarked_by', models.ManyToManyField(related_name='bookmarked_papers', through='scraping.BookmarkedPaper', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AddField(
            model_name='bookmarkedpaper',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paper_bookmarks', to='scraping.researchpaper'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['-publication_date'], name='scraping_re_publica_47e26b_idx'),
        ),
        migrations.AddIndex(
            model_name='researchpaper',
            index=models.Index(fields=['source'], name='scraping_re_source_a2cf32_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedpaper',
            index=models.Index(fields=['user', 'is_active'], name='scraping_bo_user_id_d01b80_idx'),
        ),
        migrations.AddIndex(
            model_name='bookmarkedpaper',
            index=models.Index(fields=['paper', 'is_active'], name='scraping_bo_paper_i_3ceaa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmarkedpaper',
            unique_together={('user', 'paper')},
        ),
    ]
