# Generated by Django 5.1.4 on 2025-01-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, help_text='Base64 encoded profile image', null=True),
        ),
    ]
