# Generated by Django 5.1.4 on 2025-01-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('PERSON', 'Person Account'), ('BOT', 'Bot Account')], default='PERSON', help_text='Type of account (Person or Bot)', max_length=20),
        ),
    ]
